### ISSUE TITLE
isue on /pv

### ISSUE THREAD

**Issue by xZoidy** [drew-pm-plugins/PrivateVaults#1]
Cannot access dynamic field "Items": Dynamic field access on pocketmine\nbt\tag\CompoundTag is no longer supported" (EXCEPTION) in "vendor/pocketmine/nbt/src/tag/NoDynamicFieldsTrait" at line 31
17.05 19:28:31 [Server] Server thread/DEBUG #0 vendor/pocketmine/nbt/src/tag/NoDynamicFieldsTrait(35): pocketmine\nbt\tag\CompoundTag->throw(string Items)
17.05 19:28:31 [Server] Server thread/DEBUG #1 plugins/PrivateVaults-master/src/PrivateVault/Main(179): pocketmine\nbt\tag\CompoundTag->__get(string Items)

**Comment by Wumpotamus** [comment]
@xZoidy I haven't updated this plugin to support the newer NBT formats for PMMP.

**Comment by Wumpotamus** [comment]
This plugin won't be updated either, I recommend using https://github.com/Muqsit/PlayerVaults
